package install

import (
	"bytes"
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"text/template"

	"github.com/opslify-com/opslifyd/internal/env"
	"gopkg.in/yaml.v3"
)

// Artifact filenames written into the target project directory.
const (
	EnvManifestName = "opslify.env.yaml"
	DevboxName      = "devbox.json"
	FlakeName       = "flake.nix"
)

// EnvManifest is the human-facing declared toolset written to opslify.env.yaml.
// It mirrors the env.ToolSelection that drives F0.2 but is annotated for
// readability (nix package per tool) and versioned for future migration.
type EnvManifest struct {
	Version         string         `yaml:"version"`
	BaseImageDigest string         `yaml:"base_image_digest,omitempty"`
	Tools           []ManifestTool `yaml:"tools"`
}

// ManifestTool is one declared tool in the manifest.
type ManifestTool struct {
	NixPackage string `yaml:"nix_package"`
	Version    string `yaml:"version,omitempty"`
}

// EnvManifestSchemaVersion versions the declared-toolset document.
const EnvManifestSchemaVersion = "v1"

// BuildEnvManifest converts an env.ToolSelection into the declarative manifest.
func BuildEnvManifest(sel env.ToolSelection) EnvManifest {
	m := EnvManifest{Version: EnvManifestSchemaVersion, BaseImageDigest: sel.BaseImageDigest}
	for _, t := range sel.Tools {
		m.Tools = append(m.Tools, ManifestTool{NixPackage: t.Name, Version: t.Version})
	}
	return m
}

// MarshalEnvManifest renders the manifest as YAML.
func MarshalEnvManifest(m EnvManifest) ([]byte, error) {
	b, err := yaml.Marshal(m)
	if err != nil {
		return nil, fmt.Errorf("install: marshal env manifest: %w", err)
	}
	return b, nil
}

// BuildDevbox renders a devbox.json from the selection. The "name@version"
// package syntax pins a version when provided (matching F0.2's composer), else
// "@latest" lets the pinned nixpkgs input decide.
func BuildDevbox(sel env.ToolSelection) ([]byte, error) {
	pkgs := make([]string, 0, len(sel.Tools))
	for _, t := range sel.Tools {
		if t.Version != "" {
			pkgs = append(pkgs, t.Name+"@"+t.Version)
		} else {
			pkgs = append(pkgs, t.Name+"@latest")
		}
	}
	doc := map[string]any{"packages": pkgs}
	b, err := json.MarshalIndent(doc, "", "  ")
	if err != nil {
		return nil, fmt.Errorf("install: marshal devbox.json: %w", err)
	}
	return b, nil
}

var flakeTmpl = template.Must(template.New("flake").Parse(`{
  description = "opslify toolchain (generated by opslify init)";
  inputs.nixpkgs.url = "github:NixOS/nixpkgs/nixos-unstable";
  outputs = { self, nixpkgs }:
    let
      systems = [ "x86_64-linux" "aarch64-linux" ];
      forAll = f: nixpkgs.lib.genAttrs systems (s: f nixpkgs.legacyPackages.${s});
    in {
      packages = forAll (pkgs: {
        toolchain = pkgs.buildEnv {
          name = "opslify-toolchain";
          paths = with pkgs; [
{{- range .Tools }}
            {{ .Name }}
{{- end }}
          ];
        };
      });
    };
}
`))

// BuildFlake renders a flake.nix for the selection (the alternative F0.2 input).
func BuildFlake(sel env.ToolSelection) ([]byte, error) {
	var buf bytes.Buffer
	if err := flakeTmpl.Execute(&buf, sel); err != nil {
		return nil, fmt.Errorf("install: render flake.nix: %w", err)
	}
	return buf.Bytes(), nil
}

// WriteArtifacts writes opslify.env.yaml, devbox.json and flake.nix into dir.
// Files are non-secret and written 0644. Overwrite is gated by the caller.
func WriteArtifacts(dir string, sel env.ToolSelection) error {
	manifest, err := MarshalEnvManifest(BuildEnvManifest(sel))
	if err != nil {
		return err
	}
	devbox, err := BuildDevbox(sel)
	if err != nil {
		return err
	}
	flake, err := BuildFlake(sel)
	if err != nil {
		return err
	}
	files := map[string][]byte{
		filepath.Join(dir, EnvManifestName): manifest,
		filepath.Join(dir, DevboxName):      devbox,
		filepath.Join(dir, FlakeName):       flake,
	}
	for p, b := range files {
		if err := os.WriteFile(p, b, 0o644); err != nil {
			return fmt.Errorf("install: write %s: %w", filepath.Base(p), err)
		}
	}
	return nil
}
