{
  description = "opslify toolchain (generated by opslify init)";
  inputs.nixpkgs.url = "github:NixOS/nixpkgs/nixos-unstable";
  outputs = { self, nixpkgs }:
    let
      systems = [ "x86_64-linux" "aarch64-linux" ];
      forAll = f: nixpkgs.lib.genAttrs systems (s: f nixpkgs.legacyPackages.${s});
    in {
      packages = forAll (pkgs: {
        toolchain = pkgs.buildEnv {
          name = "opslify-toolchain";
          paths = with pkgs; [
            curl
            git
            go
            jq
            kubectl
          ];
        };
      });
    };
}
